
name: 'Build src'
description: 'Build src!'
runs:
  using: "composite"
  steps:
    - name: Build R package
      run: |
        R CMD build .
      shell: bash
      
    - name: Run R CMD check
      run: |
        R CMD check --no-manual --no-build-vignettes --no-vignettes --ignore-vignettes *.tar.gz
      shell: bash
      env:
        _R_CHECK_CRAN_INCOMING_: false
        _R_CHECK_CRAN_INCOMING_REMOTE_: false
