name: Build fixed version Docker images

env:
  REGISTRY: ghcr.io

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Deploy Docker Images
    
    
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              src_image: "rocker/r-ver:4.0.4", 
              cran_url: "https://packagemanager.rstudio.com/cran/2021-04-20",
              tag: "rbmi:r404",
              mmrm_version : "v0.1.3"
            }
          - {
              src_image: "rocker/r-ver:4.1.0", 
              cran_url: "https://packagemanager.rstudio.com/cran/2021-08-04",
              tag: "rbmi:r410",
              mmrm_version : "v0.1.3"
            }

    # Token permissions
    permissions:
      contents: read
      packages: write

    # Build steps
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: docker-cache-${{ matrix.config.tag }}

      
      - name: debug
        run: |
          echo push = ${{ github.event_name == 'push' }}
          echo tag = ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.config.tag }}
          echo IMAGE=${{ matrix.config.src_image }}
          echo CRANURL=${{ matrix.config.cran_url }}
          echo MMRM_VERSION=${{ matrix.config.mmrm_version }}

      - name: Build and push image 
        uses: docker/build-push-action@v2
        with:
          context: ./misc/docker
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.config.tag }}
          build-args: |
            IMAGE=${{ matrix.config.src_image }}
            CRANURL=${{ matrix.config.cran_url }}
            MMRM_VERSION=${{ matrix.config.mmrm_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Fix bug where docker cache just continiously grows as it doesn't purge older layers
      # That are no longer in use
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#local-cache
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
