

on:
  pull_request:
    paths-ignore:
      - 'misc/**'
    branches:
      - main
      - master

name: Check Pull Requests (Master)

jobs:

  rcmdcheck:

    strategy:
      fail-fast: true
      matrix:
        config:
          - { R: "devel", os: "ubuntu-20.04"}
          - { R: "release", os: "macos-latest"}
          - { R: "release", os: "windows-latest"}
          - { R: "release", os: "ubuntu-20.04"}

    runs-on: ${{ matrix.config.os }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_TEST_NIGHTLY: 'FALSE' 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v1
        id: install-r
        with:
          r-version: ${{ matrix.config.R }}
      
      - name: Install nlopt
        if: ${{ matrix.config.os == 'windows-latest' }}
        shell: bash
        run: |
          pacman -Sy
          pacman -S mingw-w64-x86_64-nlopt

      - uses: r-lib/actions/setup-r-dependencies@v1
        name: Install R package dependencies
        with:
          cache-version: 2
          extra-packages: |
            remotes
            rcmdcheck

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning")
        shell: Rscript {0}
