

on:
  workflow_dispatch:

name: Check for CRAN

jobs:

  rcmdcheck:

    strategy:
      fail-fast: true
      matrix:
        config:
          - { R: "devel", os: "ubuntu-20.04"}
          - { R: "release", os: "macos-latest"}
          - { R: "release", os: "windows-latest"}
          - { R: "release", os: "ubuntu-20.04"}

    runs-on: ${{ matrix.config.os }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_TEST_FULL: 'FALSE' 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        id: install-r
        with:
          r-version: ${{ matrix.config.R }}

      - name: Prevent Windows from installing non-binary packages
        if: ${{ matrix.config.os == 'windows-latest'  }}
        shell: bash
        run: |
          echo 'options(install.packages.check.source = "no")' >>  .Rprofile

      - uses: r-lib/actions/setup-r-dependencies@v2
        name: Install R package dependencies
        with:
          cache-version: 2
          extra-packages: |
            remotes

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Check
        uses: ./.github/actions/rcmdcheck
        with:
          slim: false
