

on:
  pull_request:
    paths-ignore:
      - 'misc/**'

name: On Pull Request

jobs:

  rcmdcheck:

    strategy:
      fail-fast: true
      matrix:
       config:
         - { image: "ghcr.io/${{ github.repository_owner }}/rbmi:r404"}
         - { image: "ghcr.io/${{ github.repository_owner }}/rbmi:r410"}


    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.config.image }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_TEST_NIGHTLY: 'FALSE'

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Build src
        uses: ./.github/actions/build-src

      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--no-build-vignettes", "--no-vignettes", "--ignore-vignettes"),
            error_on = "warning",
            env = c("_R_CHECK_CRAN_INCOMING_" = FALSE, "_R_CHECK_CRAN_INCOMING_REMOTE_" = FALSE)
          )
        shell: Rscript {0}


  vignettes:
    strategy:
      fail-fast: true
      matrix:
       config:
         - { image: "ghcr.io/${{ github.repository_owner }}/rbmi:r404"}
         - { image: "ghcr.io/${{ github.repository_owner }}/rbmi:r410"}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.config.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: testthat
        run: |
          Rscript ./vignettes/build.R
