

on:
  schedule:
    - cron: '0 4 * * 1'

name: On Weekly

jobs:
  
  rcmdcheck-cran:
    strategy:
      fail-fast: true
      matrix:
       config:
         - { image: "ghcr.io/${{ github.repository_owner }}/rbmi:r404"}
         - { image: "ghcr.io/${{ github.repository_owner }}/rbmi:r410"}

    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.config.image }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_TEST_NIGHTLY: 'TRUE' 

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: cran

      - name: Check
        uses: ./.github/actions/rcmdcheck-slim
  
  
  
  rcmdcheck-main:
    strategy:
      fail-fast: true
      matrix:
       config:
         - { image: "ghcr.io/${{ github.repository_owner }}/rbmi:r404"}
         - { image: "ghcr.io/${{ github.repository_owner }}/rbmi:r410"}

    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.config.image }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_TEST_NIGHTLY: 'TRUE' 

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Check
        uses: ./.github/actions/rcmdcheck-slim

