# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on: push

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
       include:
         - v1: 10.x
           v2: "prod"
         - v1: 12.x
           v2: "dev"    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - run: echo $v1 ; echo $v2
      
      
      
      
      # - name: Install dependencies
      #   run: |
      #     install.packages(c("remotes", "rcmdcheck"))
      #     remotes::install_deps(dependencies = TRUE)
      #   shell: Rscript {0}
      # - name: Check
      #   run: |
      #     options(crayon.enabled = TRUE)
      #     rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
      #   shell: Rscript {0}
